src/lists/urls.py
from django.urls import path

from lists.views import ListsList, ListCreate, ListUpdate, ListDelete

app_name = "lists"

urlpatterns = [
	path('', ListsList.as_view(), name="list"),
	path('create/', ListCreate.as_view(), name="create"),
	path('delete/<int:pk>', ListDelete.as_view(), name="delete"),
	path('update/<int:pk>', ListUpdate.as_view(), name="update"),
]

src/tasks/urls.py
from django.urls import path

from tasks.views import TaskCreate, TaskUpdate, TaskDelete, close, reopen, statistics

app_name = "tasks"

urlpatterns = [
	path('create/<int:list>/', TaskCreate.as_view(), name="create"),
	path('update/<int:pk>', TaskUpdate.as_view(), name="update"),
	path('delete/<int:pk>', TaskDelete.as_view(), name="delete"),
	path('close/<int:pk>', close, name="close"),
	path('reopen/<int:pk>', reopen, name="reopen"),
	path('stats/', statistics, name='stats')
]

src/todo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from todo.views import index


urlpatterns = [
	path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
	path('', index, name="index"),
	path('accounts/', include('allauth.urls')),
	path('tasks/', include('tasks.urls', namespace="tasks")),
	path('lists/', include('lists.urls', namespace="lists")),
)

src/lists/models.py
from django.db import models
from django.contrib.auth.models import User


class List(models.Model):
	name = models.CharField(max_length=20, blank=False)
	user = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name="lists")

	class Meta:
		unique_together = ["name", "user"]

	def __str__(self):
		return self.name

	def get_tasks_opened(self):
		return self.tasks.filter(closed=False)

	def get_tasks_closed(self):
		return self.tasks.filter(closed=True)

src/tasks/models.py
from django.db import models
from datetime import date


class Task(models.Model):
	list = models.ForeignKey(to='lists.List', on_delete=models.CASCADE, related_name='tasks', blank=False)
	closed = models.BooleanField(blank=False, default=False)
	title = models.CharField(max_length=40, blank=False)
	details = models.TextField(max_length=125, blank=True)
	due_date = models.DateField(null=True, blank=True)
	favorite = models.BooleanField(null=True, blank=True, default=False)

	def __str__(self):
		return self.title

	def close(self):
		self.closed = True
		self.save()

	def reopen(self):
		self.closed = False
		self.save()

	def due_date_is_past(self):
		if not self.due_date or self.due_date >= date.today():
			return False
		return True

src/tasks/forms.py
from django import forms
from tasks.models import Task


class TaskForm(forms.ModelForm):

	class Meta:
		model = Task
		fields = ["title", "details", "due_date", "favorite"]

		widgets = {
			'due_date': forms.DateInput(format='%Y-%m-%d', attrs={'placeholder': 'Select a date', 'type': 'date'})
		}

src/lists/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from rules.contrib.views import PermissionRequiredMixin
from django.urls import reverse_lazy

from lists.models import List


class ListsList(LoginRequiredMixin, ListView):
	model = List
	context_object_name = "lists"
	success_url = reverse_lazy("lists:list")

	def get_queryset(self, *args, **kwargs):
		return List.objects.filter(user=self.request.user)


class ListCreate(LoginRequiredMixin, CreateView):
	model = List
	template_name = "lists/list_create_form.html"
	success_url = reverse_lazy("lists:list")
	fields = ["name"]

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super().form_valid(form)


class ListUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
	model = List
	template_name = "lists/list_update_form.html"
	success_url = reverse_lazy("lists:list")
	fields = ["name"]
	permission_required = "lists.change_list"


class ListDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
	model = List
	template_name = "lists/list_delete_form.html"
	success_url = reverse_lazy("lists:list")
	permission_required = "lists.change_list"

src/tasks/views.py
import json

from django.shortcuts import redirect
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from rules.contrib.views import PermissionRequiredMixin, objectgetter
from rules.contrib.views import permission_required
from django.db.models import Count, Q
from django.shortcuts import render
from django.utils.translation import gettext

from tasks.models import Task
from lists.models import List
from tasks.forms import TaskForm


class TaskCreate(LoginRequiredMixin, CreateView):
	model = Task
	form_class = TaskForm
	template_name = "tasks/task_create_form.html"
	success_url = reverse_lazy("lists:list")

	def form_valid(self, form):
		form.instance.list = List.objects.get(pk=self.kwargs["list"])
		return super().form_valid(form)


class TaskUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
	model = Task
	form_class = TaskForm
	template_name = "tasks/task_update_form.html"
	permission_required = "tasks.change_task"
	success_url = reverse_lazy("lists:list")


class TaskDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
	model = Task
	permission_required = "tasks.delete_task"
	success_url = reverse_lazy("lists:list")
	template_name = "lists/list_list.html"


@login_required()
@permission_required("tasks.change_task", fn=objectgetter(Task, "pk"), raise_exception=True)
def close(request, pk):
	Task.objects.get(pk=pk).close()
	return redirect("lists:list")


@login_required
@permission_required("tasks.change_task", fn=objectgetter(Task, "pk"), raise_exception=True)
def reopen(request, pk):
	Task.objects.get(pk=pk).reopen()
	return redirect("lists:list")


@login_required
def statistics(request):
	dataset = Task.objects.filter(list__user=request.user).values("list__name").annotate(
		closed_count=Count("list", filter=Q(closed=True)),
		not_closed_count=Count("list", filter=Q(closed=False))
	)

	lists = []
	closed_series_data = []
	not_closed_series_data = []

	for entry in dataset:
		lists.append(entry['list__name'])
		closed_series_data.append(entry['closed_count'])
		not_closed_series_data.append(entry['not_closed_count'])

	closed_series = {
		'name': gettext('Fermées'),
		'data': closed_series_data,
		'color': 'green'
	}

	not_closed_series = {
		'name': gettext('Ouvertes'),
		'data': not_closed_series_data,
		'color': 'blue'
	}

	chart = {
		'chart': {'type': 'column'},
		'title': {'text': gettext('Tâches par statut')},
		'xAxis': {'categories': lists},
		'series': [closed_series, not_closed_series]
	}

	dump = json.dumps(chart)

	return render(request, 'tasks/statistics.html', {'chart': dump})

src/todo/views.py
from django.shortcuts import render


def index(request):
	return render(request, "index.html")

src/lists/templates/lists/list_create_form.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<br>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans 'Créer' %}">
</form>

{% endblock %}

src/lists/templates/lists/list_delete_form.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<br>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{% blocktranslate with list_name=object|upper%} Etes-vous sûr de vouloir supprimer la liste {{ list_name }} {% endblocktranslate %}</p>
    {{ form.as_p }}
    <input type="submit" value="{% trans 'Supprimer' %}">
</form>
{% endblock %}

src/lists/templates/lists/list_list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

<br>
<a href="{% url 'lists:create' %}">
    {% blocktranslate %} Créer une nouvelle liste {% endblocktranslate %}
</a>
<br>
<br>
<div class="row row-cols-auto g-4">
    {% for list in lists %}
    <div class="col">
        <div class="card border-secondary" style="width: 18rem;">
            <div class="card-header">
                {{ list.name|upper }}
                <a href="{% url 'lists:update' pk=list.pk %}"><i
                        class="bi bi-pencil-square"></i></a>
                <a href="{% url 'lists:delete' pk=list.pk %}"><i class="bi bi-trash"></i></a>

            </div>
            <ul class="list-group list-group-flush">
                {% for task in list.get_tasks_opened %}

                <li class="list-group-item">
                    <a href="{% url 'tasks:close' pk=task.pk %}"><i class="bi bi-circle"></i></a>
                    {{ task.title }}
                    {% if task.due_date_is_past %}
                    <i class="bi bi-hourglass-bottom text-danger"></i>
                    {% endif %}

                    <a href="{% url 'tasks:update' pk=task.pk %}"><i
                            class="bi bi-pencil-square"></i></a>
                </li>
                {% endfor %}
            </ul>

            {% if list.get_tasks_closed %}

            <div class="accordion accordion-flush" id="accordionFlushExample">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-heading{{list.name}}">
                        <button class="accordion-button collapsed" type="button"
                                data-bs-toggle="collapse"
                                data-bs-target="#flush-collapse{{list.pk}}" aria-expanded="false"
                                aria-controls="flush-collapse{{list.pk}}">
                            {% trans "Terminée(s)" %}
                        </button>
                    </h2>
                    <div id="flush-collapse{{list.pk}}" class="accordion-collapse collapse"
                         aria-labelledby="flush-heading{{list.pk}}"
                         data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body">
                            <ul class="list-group list-group-flush">

                                {% for task in list.get_tasks_closed %}

                                <li class="list-group-item">
                                    <div class="row">
                                        <div class="col-md-auto my-auto">
                                            <a href="{% url 'tasks:reopen' pk=task.pk %}"><i
                                                    class="bi bi-check"></i></a>
                                            <i>{{ task.title }}</i>
                                        </div>
                                        <div class="col-md-auto">
                                            <form method="POST" action="{% url 'tasks:delete' pk=task.pk %}">
                                                {% csrf_token %}
                                                <button type="submit" class="btn btn-link btn-sm"><i class="bi bi-trash"></i></button>
                                            </form>
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            {% endif %}

            <div class="card-footer">
                <a href="{% url 'tasks:create' list=list.pk %}">
                    {% blocktranslate %} Créer une tâche {% endblocktranslate %}
                    <i class="bi bi-plus-square"></i></a>
            </div>

        </div>
    </div>


    {% endfor %}
</div>

{% endblock %}

src/lists/templates/lists/list_update_form.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<br>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans 'Mettre à jour' %}">
</form>
{% endblock %}

src/tasks/templates/tasks/statistics.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}


<div id="stats" style="width:100%; height:400px;"></div>

<script>
      Highcharts.chart('stats', {{ chart|safe }});

</script>

{% endblock %}

src/tasks/templates/tasks/task_create_form.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<br>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans 'Créer' %}">
</form>
{% endblock %}

src/tasks/templates/tasks/task_update_form.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<br>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="{% trans 'Mettre à jour' %}">
</form>

{% endblock %}

src/todo/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>TODO</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <style>

     .accordion-body {
            padding: 0;
        }







    </style>


</head>

<body>
{% load i18n %}
<nav class="py-2 bg-light border-bottom">
    <div class="container d-flex flex-wrap">
        <ul class="nav me-auto">
            <li class="nav-item"><a href="{% url 'index' %}" class="nav-link link-dark px-2 active"
                                    aria-current="page"><i class="bi bi-house-door-fill"></i></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    {% trans "Langue" %}
                </a>
                <ul class="dropdown-menu">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}

                    {% for lang in languages %}
                    <li>
                        <a class="dropdown-item"
                           href="/{{ lang.code }}/{{request.get_full_path|slice:'4:'}}">
                            {{ lang.name_translated }}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'lists:list' %}" class="nav-link link-dark px-2 active" aria-current="page">{% trans "Tâches" %}</a>
            </li>
            <li class="nav-item"><a href="{% url 'tasks:stats' %}" class="nav-link link-dark px-2 active" aria-current="page">{% trans "Statistiques" %}</a>
            </li>
            {% endif %}
        </ul>
        <ul class="nav">
            {% load socialaccount %}
            {% if request.user.is_authenticated %}
            {% get_social_accounts user as accounts %}
            {% if not accounts %}
            <li class="nav-link link-dark px-2">{% trans "Bienvenue" %} <a
                    href="/accounts/password/set/">{{request.user.email}}</a>
            </li>
            {% else %}
            <li class="nav-link link-dark px-2">{% trans "Bienvenue" %} {{request.user.email}}</li>
            {% endif %}
            <li class="nav-item"><a href="{% url 'account_logout' %}" class="btn btn-outline-primary me-2">{% trans "Se déconnecter" %}</a></li>

            {% else %}
            <li class="nav-item"><a href="{% url 'account_login' %}" class="btn btn-outline-primary me-2">{% trans "Se connecter" %}</a></li>
            <li class="nav-item"><a href="{% url 'account_signup' %}" class="btn btn-outline-primary me-2">{% trans "S'inscrire" %}</a></li>
            {% endif %}
        </ul>
    </div>
</nav>


</div>


<div class="container">
    {% block content %}
    {%endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>


</body>
</html>

src/todo/templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

<h1>{% trans "Bienvenue !" %}</h1>
{% endblock %}